# Graph Representation

In [1]:
import numpy as np

def myFunc(file, graph_selection):
    
    #open file 
    f = open(file)
    #read the lines of the fule 
    str_data = f.readlines()
    #for each element in the file, split the string and convert to float 
    data = [[float(element) for element in str.split()] for str in str_data]
    
    #edge list 
    if graph_selection == 1:
        print('Edge List for {}'.format(file))
        G = edgeList(data)
        
    #Adjacency matrix
    if graph_selection == 2:
        print('Adjacency Matrix for {}'.format(file))
        G = adjacencyMatrix(data)
    
    #Adjacency Structure
    if graph_selection == 3:
        print('Adjacency Structure for {}'.format(file))
        G = adjacencyStructure(data)
        
    #incidence Matrix 
    if graph_selection == 4:
        print('Incidence Matrix for {}'.format(file))
        G = incidenceMatrix(data, edgeList(data))
    
    #return graph
    return G

In [2]:
def edgeList(data):
    
    #create empty edge list 
    edge_list = []
    
    #loop through grf data
    for i in data:
        #loop through edges in formated grf file 
        for j in i[3:]:
            #assign the edge to the node
            edge = [i[0],j]
            #if first node is less than paired node 
            #this removes duplicates
            if (edge[0] < edge[1]):
                #add node and its corresponding node 
                #that shares an edge 
                edge_list.append(edge)

    #return edge list
    return edge_list

In [3]:
def adjacencyMatrix(data):
    
    #grab all nodes from grf file 
    nodes = [sub_list[0] for sub_list in data]
    #set var n to the length of nodes
    n = len(nodes)
    
    #initialize empty lists to hold pairs of edges 
    edge_1= []
    edge_2 = []
    
    #loop through data 
    for i in data:
        #loop through paired edges 
        for j in i[3:]:
            #assign edge to node
            mat = [i[0],j]
            #append edges 
            edge_1.append(mat[0])
            edge_2.append(mat[1])
            
    #create empty adjacency matrix with zeros
    adj_matrix = np.zeros((n,n))
    
    #loop through edge list 
    for i in range(len(edge_1)):
        #unpack list and convert to int to be able to index
        u = int(edge_1[i])
        v = int(edge_2[i])
        #assign 1.0 to connected nodes 
        adj_matrix[u-1][v-1] = 1.0

    #return adjacency matrix
    return adj_matrix

In [4]:
def adjacencyStructure(data):
    
    #create lists of nodes and adjacencent nodes 
    nodes = [sub_list[0] for sub_list in data]
    adj_nodes = [sub_list[3:] for sub_list in data]

    #zip up lists and convert to dict to form structure 
    adj_struct = dict(zip(nodes, adj_nodes))

    #output graph 
    return adj_struct

In [5]:
def incidenceMatrix(data, edge_list):
    
    #get all nodes from grf format
    nodes = [sub_list[0] for sub_list in data]
    #get the length of all nodes for size of matrix 
    n = len(nodes)
    
    #initialize incidence matrix by how many edges there are and nodes
    #4x5
    inc_matrix = np.zeros((len(edge_list), n))
    
    for i in range(len(edge_list)):
        for j in range(len(edge_list[i])):
            inc_matrix[i, int(edge_list[i][j] - 1)] = 1
            inc_matrix[i, int(edge_list[i][j] - 1)] = 1

    #output graph  
    return inc_matrix

## Converting GRF format

In [6]:
#Edge list 
myFunc('graph.grf', 1)

Edge List for graph.grf


[[1.0, 2.0], [1.0, 3.0], [2.0, 3.0], [3.0, 4.0]]

In [7]:
#Adjacency matrix
myFunc('graph.grf', 2)

Adjacency Matrix for graph.grf


array([[0., 1., 1., 0., 0.],
       [1., 0., 1., 0., 0.],
       [1., 1., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
#Adjacency structure
myFunc('graph.grf', 3)

Adjacency Structure for graph.grf


{1.0: [2.0, 3.0], 2.0: [1.0, 3.0], 3.0: [1.0, 2.0, 4.0], 4.0: [3.0], 5.0: []}

In [9]:
#incidence matrix 
myFunc('graph.grf', 4)

Incidence Matrix for graph.grf


array([[1., 1., 0., 0., 0.],
       [1., 0., 1., 0., 0.],
       [0., 1., 1., 0., 0.],
       [0., 0., 1., 1., 0.]])

## Converting GRF format of South America 

In [10]:
#Edge list 
myFunc('southAmerica.grf', 1)

Edge List for southAmerica.grf


[[1.0, 2.0],
 [1.0, 3.0],
 [1.0, 4.0],
 [1.0, 8.0],
 [1.0, 11.0],
 [2.0, 3.0],
 [2.0, 4.0],
 [2.0, 8.0],
 [2.0, 9.0],
 [3.0, 5.0],
 [3.0, 7.0],
 [3.0, 8.0],
 [3.0, 9.0],
 [3.0, 10.0],
 [3.0, 11.0],
 [3.0, 12.0],
 [4.0, 9.0],
 [5.0, 6.0],
 [5.0, 9.0],
 [5.0, 12.0],
 [6.0, 9.0],
 [7.0, 10.0],
 [7.0, 12.0]]

In [11]:
#Adjacency matrix
myFunc('southAmerica.grf', 2)

Adjacency Matrix for southAmerica.grf


array([[0., 1., 1., 1., 0., 0., 0., 1., 0., 0., 1., 0.],
       [1., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1.],
       [1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0.]])

In [12]:
#Adjacency Structure
myFunc('southAmerica.grf', 3)

Adjacency Structure for southAmerica.grf


{1.0: [2.0, 3.0, 4.0, 8.0, 11.0],
 2.0: [1.0, 3.0, 4.0, 8.0, 9.0],
 3.0: [1.0, 2.0, 5.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0],
 4.0: [1.0, 2.0, 9.0],
 5.0: [3.0, 6.0, 9.0, 12.0],
 6.0: [5.0, 9.0],
 7.0: [3.0, 10.0, 12.0],
 8.0: [1.0, 2.0, 3.0],
 9.0: [2.0, 3.0, 4.0, 5.0, 6.0],
 10.0: [3.0, 7.0],
 11.0: [1.0, 3.0],
 12.0: [3.0, 5.0, 7.0]}

In [13]:
#incidence matrix 
myFunc('southAmerica.grf', 4)

Incidence Matrix for southAmerica.grf


array([[1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1.,

## Counting Walks

We can use an adjacency matrix to count walks. The *ij*'th entry of $A^kv$ will give the number of k-length paths connecting to nodes *i and j*. 

In [14]:
#Count the number of walks from Chile to Venezuela 

#create the adjacency matrix for the South America grf graph 
A = myFunc('southAmerica.grf', 2)

#vector v is the starting point at Chile 
#in this case Chile is the fourth country in the grf file 
#thus I create a vector v to be zero except for a 1 in the 
#entry corresponging to node B (Chile)
v = [0,0,0,1,0,0,0,0,0,0,0,0]

#to get the fewest number of countries that I must visit, 
#including Chile and Venezuela I raise A to the power of 3
#looking at a map the min num of countries is 4 (including c and v)
#power of 2 doesnt work since there are zero terms in the list 
#which indicate that the graph isnt connected
walk_c2v = np.dot(np.linalg.matrix_power(A, 3), np.transpose(v))[-1]

#all shortest walks from Chile to Venezuela 
all_walks = [int(i) for i in np.dot(np.linalg.matrix_power(A, 3), np.transpose(v))]

print('Fewest number of countries that must be visited, including Chile and Venezuela is {}'.format(int(walk_c2v)))
print('\nAll shortest walks from Chile to Venezuela\n{}'.format(all_walks))

Adjacency Matrix for southAmerica.grf
Fewest number of countries that must be visited, including Chile and Venezuela is 4

All shortest walks from Chile to Venezuela
[11, 10, 8, 4, 5, 2, 3, 6, 10, 3, 4, 4]


In [15]:
np.dot(np.linalg.matrix_power(A, 8), np.transpose(v)).sum()

137225.0

We can generalize the method used above and remove dependence on vector $v$. Let A be the adjacency matrix from a graph $G$. Then $A^k_{i,j}$ counts the number of walks of length k from node *i to node j*. To find the total number of walks of size 8, just sum the total number of walks.

In [16]:
#different walks of size 8
num_walks8 = np.linalg.matrix_power(A, 8).sum()
print('The amount of different possible walks of size 8 is {:,} walks'.format(int(num_walks8)))

The amount of different possible walks of size 8 is 1,909,772 walks


# Traveling Salesman Problem

In [26]:
#read the text file using list comprehension
data = [[float(x) for x in str.split()] for str in open('salesman.txt').readlines()]

#read the edge list of the txt file 
edges = [x[0:2] for x in data]

for i in edges:
    all_perms = list(itertools.permutations(i))
    all_perms = [list(x) for x in all_perms]
    print(all_perms)

#read in the edge weights of the txt file 
weights = [x[2] for x in data]

[[1.0, 2.0], [2.0, 1.0]]
[[1.0, 3.0], [3.0, 1.0]]
[[1.0, 6.0], [6.0, 1.0]]
[[1.0, 7.0], [7.0, 1.0]]
[[1.0, 8.0], [8.0, 1.0]]
[[2.0, 3.0], [3.0, 2.0]]
[[2.0, 7.0], [7.0, 2.0]]
[[3.0, 4.0], [4.0, 3.0]]
[[3.0, 8.0], [8.0, 3.0]]
[[4.0, 8.0], [8.0, 4.0]]
[[5.0, 6.0], [6.0, 5.0]]
[[5.0, 7.0], [7.0, 5.0]]
[[5.0, 8.0], [8.0, 5.0]]
[[6.0, 7.0], [7.0, 6.0]]
[[6.0, 8.0], [8.0, 6.0]]


In [28]:
import itertools
mylist = [0,1,2]
all_perms = list(itertools.permutations(mylist)) # list of tuples
all_perms = [list(x) for x in all_perms] # convert to list of lists
all_perms

[[0, 1, 2], [0, 2, 1], [1, 0, 2], [1, 2, 0], [2, 0, 1], [2, 1, 0]]

Combinatorial computation: studies objects which we can think of as arrangements of items 
Permutations: need permutations of N items (ordered sequence) and pick the smallest one 
The TSP requires us to choose the best itinerary for visting N cities, which is a permutation. Each permutation is an itinerary, that is, the order in which we vist the cities. 
    
Random Permutation - we start with the task of choosing a permutation at random. 
The algo for a random permutation of orderN is 
    Initalize P to [1, 2, ..., N]
    
    for I = N down to 2
        choose a random int j between 1 and I
        swap P(I) and P(J)