In [193]:
import numpy as np

def myFunc(file, graph_selection):
    
    #open file 
    f = open(file)
    #read the lines of the fule 
    str_data = f.readlines()
    #for each element in the file, split the string and convert to float 
    data = [[float(element) for element in str.split()] for str in str_data]
    
    #edge list 
    if graph_selection == 1:
        G = edgeList(data)
        
    #Adjacency matrix
    if graph_selection == 2:
        G = adjacencyMatrix(data)
    
    #Adjacency Structure
    if graph_selection == 3:
        G = adjacencyStructure(data)
        
    #incidence Matrix 
    if graph_selection == 4:
        G = incidenceMatrix(data, edgeList(data))
    
    #return graph
    return G

In [194]:
def edgeList(data):
    
    edge_list = []
    
    for i in data:
        for j in i[3:]:
            edge = [i[0],j]
            if (edge[0] < edge[1]):
                edge_list.append(edge)

    return edge_list

In [304]:
def adjacencyMatrix(data):
    
    nodes = [sub_list[0] for sub_list in data]
    n = len(nodes)
    
    edge_1= []
    edge_2 = []

    for i in data:
        for j in i[3:]:
            mat = [i[0],j]
            edge_1.append(mat[0])
            edge_2.append(mat[1])
            
    #create empty adjacency matrix with zeros
    adj_matrix = np.zeros((n,n))

    for i in range(len(edge_1)):
        u = int(edge_1[i])
        v = int(edge_2[i])
        adj_matrix[u-1][v-1] = 1.0

    return adj_matrix

In [305]:
def adjacencyStructure(data):
    
    #create lists of nodes and adjacencent nodes 
    nodes = [sub_list[0] for sub_list in data]
    adj_nodes = [sub_list[3:] for sub_list in data]

    #zip up lists and convert to dict to form structure 
    adj_struct = dict(zip(nodes, adj_nodes))

    #output graph 
    return adj_struct

In [306]:
def incidenceMatrix(data, edge_list):
    
    #get all nodes from grf format
    nodes = [sub_list[0] for sub_list in data]
    #get the length of all nodes for size of matrix 
    n = len(nodes)
    
    #initialize incidence matrix by how many edges there are and nodes
    #4x5
    inc_matrix = np.zeros((len(edge_list), n))
    
    for i in range(len(edge_list)):
        for j in range(len(edge_list[i])):
            inc_matrix[i, int(edge_list[i][j] - 1)] = 1
            inc_matrix[i, int(edge_list[i][j] - 1)] = 1

    #output graph  
    return inc_matrix

In [307]:
#Edge list 
myFunc('graph.grf', 1)

[[1.0, 2.0], [1.0, 3.0], [2.0, 3.0], [3.0, 4.0]]

In [308]:
#Adjacency matrix
myFunc('graph.grf', 2)

array([[0., 1., 1., 0., 0.],
       [1., 0., 1., 0., 0.],
       [1., 1., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [309]:
#Adjacency structure
myFunc('graph.grf', 3)

{1.0: [2.0, 3.0], 2.0: [1.0, 3.0], 3.0: [1.0, 2.0, 4.0], 4.0: [3.0], 5.0: []}

In [310]:
#incidence matrix 
myFunc('graph.grf', 4)

array([[1., 1., 0., 0., 0.],
       [1., 0., 1., 0., 0.],
       [0., 1., 1., 0., 0.],
       [0., 0., 1., 1., 0.]])

In [311]:
#Edge list 
myFunc('southAmerica.grf', 1)

[[1.0, 2.0],
 [1.0, 3.0],
 [1.0, 4.0],
 [1.0, 8.0],
 [1.0, 11.0],
 [2.0, 3.0],
 [2.0, 4.0],
 [2.0, 8.0],
 [2.0, 9.0],
 [3.0, 5.0],
 [3.0, 7.0],
 [3.0, 8.0],
 [3.0, 9.0],
 [3.0, 10.0],
 [3.0, 11.0],
 [3.0, 12.0],
 [4.0, 9.0],
 [5.0, 6.0],
 [5.0, 9.0],
 [5.0, 12.0],
 [6.0, 9.0],
 [7.0, 10.0],
 [7.0, 12.0]]

In [312]:
#Adjacency matrix
myFunc('southAmerica.grf', 2)

array([[0., 1., 1., 1., 0., 0., 0., 1., 0., 0., 1., 0.],
       [1., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1.],
       [1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0.]])

In [313]:
#Adjacency Structure
myFunc('southAmerica.grf', 3)

{1.0: [2.0, 3.0, 4.0, 8.0, 11.0],
 2.0: [1.0, 3.0, 4.0, 8.0, 9.0],
 3.0: [1.0, 2.0, 5.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0],
 4.0: [1.0, 2.0, 9.0],
 5.0: [3.0, 6.0, 9.0, 12.0],
 6.0: [5.0, 9.0],
 7.0: [3.0, 10.0, 12.0],
 8.0: [1.0, 2.0, 3.0],
 9.0: [2.0, 3.0, 4.0, 5.0, 6.0],
 10.0: [3.0, 7.0],
 11.0: [1.0, 3.0],
 12.0: [3.0, 5.0, 7.0]}

In [314]:
#incidence matrix 
myFunc('southAmerica.grf', 4)

array([[1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1.,

In [341]:
adj_matrix = myFunc('southAmerica.grf', 2)
v = [0,0,0,1,0,0,0,0,0,0,0,0]
len(v)
np.dot(np.linalg.matrix_power(adj_matrix, 3), np.transpose(v))

array([11., 10.,  8.,  4.,  5.,  2.,  3.,  6., 10.,  3.,  4.,  4.])

In [344]:
np.dot(np.linalg.matrix_power(adj_matrix, 8), np.transpose(v)).sum()

137225.0

In [343]:
np.linalg.matrix_power(adj_matrix, 8).sum()

1909772.0